version: '2'
services:
    cloud9:
        image: kdelfour/cloud9-docker
        volumes_from:
            - data
        ports:
            - "8080:80"
    clustercontrol:
        build: ./clustercontrol
        ports:
            - "5000:80"
        volumes:
            - ./clustercontrol/.ssh:/root/.ssh/
    db:
        build: ./mariadb
        depends_on: 
            - clustercontrol
        environment:
            - MYSQL_ROOT_PASSWORD=ibdb
    db-backup:
        image: mariadb
        depends_on: 
            - clustercontrol
        environment:
            - MYSQL_ROOT_PASSWORD=ibdb
    uifd:
        image: uifd/ui-for-docker
        ports:
            - 9000:9000
        privileged: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    data:
        image: tianon/true
        volumes:
            - /home/ubuntu/workspace:/workspace
